---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: summer-k8s-rollout
spec:
  replicas: 3
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: summer-k8s-deployment
  strategy:
    canary:
      stableService: summer-k8s-service-stable
      canaryService: summer-k8s-service-canary
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {}     